// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuH6fntnzD8pJnLD65ToetMC5bKq6OV8Q',
    appId: '1:641837892555:android:0ac32ac3af6a17ac982c4e',
    messagingSenderId: '641837892555',
    projectId: 'closure-65d65',
    storageBucket: 'closure-65d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxEpPnWQ3zQTb3mxtP2q0wfZuOoaWPNLc',
    appId: '1:641837892555:ios:fe2f1d7449f37ef2982c4e',
    messagingSenderId: '641837892555',
    projectId: 'closure-65d65',
    storageBucket: 'closure-65d65.appspot.com',
    androidClientId: '641837892555-b3e6phk89q024ka9s7emcngffbf9cbo6.apps.googleusercontent.com',
    iosClientId: '641837892555-4glt7e2kuarp2n7gp375phsg0nlvaaae.apps.googleusercontent.com',
    iosBundleId: 'com.adedoyin.closure01',
  );
}
